import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import Link from "next/link";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="flex h-screen">
            {/* Sidebar (Left Pane) */}
            <aside className="w-64 bg-gray-800 text-white p-4 hidden sm:block"><Sidebar /></aside>

            {/* Main Content Area */}
            <div className="flex-1 flex flex-col">
              {/* Top Navbar */}
              <header><Navbar /></header>

              {/* Dynamic Page Content (Calendar, About, etc.) */}
              <main className="flex-1 pt-16">{children}</main>

              {/* Footer */}
              <footer className="bg-gray-900 text-white p-4">
                <Footer />
              </footer>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
